### ISSUE TITLE
[Back][Front] Validación login usuarios

### ISSUE THREAD

**Issue by andsanchez** [ThePhrontistery/py-labar#12]
Implementar una lógica para devolver un mensaje de error si el usuario y la contraseña son incorrectas en el login.

**Comment by pchocron** [comment]
Usaré Pydantic para validación

**Comment by andsanchez** [comment]
Validado ✅ 


![Image](https://github.com/ThePhrontistery/py-labar/assets/11856397/a29c5555-be85-4a87-9061-147d39c855e8)
